### ISSUE TITLE
Disable default page redirection after sign in

### ISSUE THREAD

**Issue by Lopuch** [cothema/ionic-universal-firebase-login#3]
I would like to have an option to disable redirection after sign in.
Maybe implementing a switch to disable this code?:
`
protected onAfterLogin() {
        if (this.options.afterLoginPage) {
            this.router.navigate([this.options.afterLoginPage]);
        }
    }
`

and same for the onAfterSignOut()

**Comment by miloshavlicek** [comment]
Thank you for your feedback. At this time you can override options property and setup loginPage to false and afterLoginPage also to false in BaseAuthService. I am working on some improvements and I will write it to the package docs.

**Comment by miloshavlicek** [comment]
@Lopuch See new configuration in README. You can now set:
```
UniFirebaseLoginModule.forRoot({
            afterSignInPage: false
});
```
or you can pass false to first parameter of signInVia...() method of BaseAuthenticationService
